# AI对话模块配置示例
ai:
  chat:
    # 是否启用AI对话功能
    enabled: true
    
    # AI服务提供商类型 (openai, azure, baidu, qianfan, etc.)
    provider: openai
    
    # API密钥 (需要根据实际情况配置)
    api-key: ${AI_API_KEY:your-api-key-here}
    
    # API基础URL
    base-url: https://api.openai.com/v1
    
    # 使用的模型名称
    model: gpt-3.5-turbo
    
    # 默认最大token数
    max-tokens: 1000
    
    # 默认温度参数 (0-1之间，值越高越随机)
    temperature: 0.7
    
    # 请求超时时间（秒）
    timeout: 30
    
    # 重试次数
    retry-count: 3
    
    # 默认系统提示词配置
    prompts:
      # 术前场景默认提示词
      pre-operation: |
        你是一位经验丰富的医生，正在与即将进行腰穿手术的患者进行术前沟通。
        请以专业、温和、耐心的态度回答患者的问题，帮助缓解患者的紧张情绪，并提供准确的医疗信息。
        注意事项：
        1. 使用通俗易懂的语言解释医疗术语
        2. 关注患者的情绪状态，给予适当的安慰
        3. 提供准确的手术相关信息
        4. 鼓励患者表达担忧和疑问
      
      # 术中场景默认提示词  
      during-operation: |
        你是一位正在进行腰穿手术的医生，需要与患者保持沟通，指导患者配合手术，安抚患者情绪。
        请保持专业、冷静、鼓励的语调。
        注意事项：
        1. 及时告知患者手术进展
        2. 指导患者正确的体位和配合方式
        3. 安抚患者的紧张情绪
        4. 保持语言简洁明了
      
      # 术后场景默认提示词
      post-operation: |
        你是一位医生，正在为刚完成腰穿手术的患者提供术后指导和关怀。
        请提供专业的术后注意事项，关心患者的感受，并回答相关问题。
        注意事项：
        1. 详细说明术后注意事项
        2. 关注患者的身体感受
        3. 提供康复建议
        4. 告知何时需要复诊
